### ISSUE TITLE
Create Logo Concepts

### ISSUE THREAD

**Issue by digitaltopo** [Aria-experience/aria#6]
We need a logo!

**Comment by jentoobento** [comment]
<img width="419" alt="logo concept 2" src="https://user-images.githubusercontent.com/41801164/47408833-afe36300-d715-11e8-8212-ad2526ce3183.png">

**Comment by digitaltopo** [comment]
@jentoobento I think this looks awesome so far! 

1. Have there been more updates? 
2. Do you need any feedback from the team?

My .02: I love the direction you're going! Excited to put this into the app when you're ready and if everyone is down with it!

**Comment by digitaltopo** [comment]
@mardb any update on animation?
