### ISSUE TITLE
Create Global Submission Video

### ISSUE THREAD

**Issue by digitaltopo** [Aria-experience/aria#9]
We need to create a video for our Global submission! 

It's due at **midnight local time on Sunday, October 28, 2018**

### Preparation
- [ ] Review [Judging Criteria](https://github.com/Aria-experience/aria/wiki/NASA-Space-Apps-Challenge-Resources#judging-resources)
- [ ] Review [2017 winners](https://github.com/Aria-experience/aria/wiki/NASA-Space-Apps-Challenge-Resources#2017-awards--recognitions) videos
- [ ] Write a script for the video

### Production
- [x] Find a video editor to help us?
- [x] Find camera person (Los Angeles) 
- [x] Create video clips of the app being used (with audio)
- [ ] Edit/Produce the video 
- [ ] Submit the video

### Questions
1. Do we need someone to film some short interviews for voice-over? YES: Chris Jones will film and record for us
1. Does anyone know some kids that could be pictured interacting with the app?
1. Do we have an iPad we could show being used with the app on it? YES: Melissa will use her touch screen.
1. We could also project the app onto the geodesic dome for a part of it (where we describe how we plan on expanding our medium YES: Orestis will film the dome

Video Planning Doc: 
https://docs.google.com/document/d/1pDD5Bd_p6uDOhKlY2mxcYOFT1WLpZZhzTaTmOPBQFfA/edit?usp=sharing

30 Seconds of Glory:
![30 Seconds of Glory](https://sa-media-2018.s3.amazonaws.com/media/images/30seconds_FbRUpS4.original.png)

**Let's discuss the open questions and ideas for video script in comments**

**Comment by jentoobento** [comment]
we don't have to use this one for the final submission but i think it's a good start and maybe we can find a use for it elsewhere

**Comment by jentoobento** [comment]
[aria video](https://drive.google.com/open?id=1V9bsx5WSgxWUglgdvB70An2Ltw279RsM)

**Comment by digitaltopo** [comment]
Locking this issue so we can keep our resources together for in the google doc:
https://docs.google.com/document/d/1pDD5Bd_p6uDOhKlY2mxcYOFT1WLpZZhzTaTmOPBQFfA/edit?usp=sharing

Will leave the issue for [project progress tracking](https://github.com/orgs/Aria-experience/projects/2)
